application:
  signature:
    secret-key: test-secret-key
  aws:
    sns:
      formr-parta-submitted: dummy
      formr-partb-submitted: dummy
    sqs:
      coj-received: dummy
      delete-event: dummy
      notification-event: dummy
      profile-move: dummy
  schedules:
    publish-all-ltfts: "-"

mongock:
  enabled: false

spring:
  cloud:
    aws:
      region:
        static: eu-west-2
      sqs:
        enabled: false
